export const enum ConfigParams {
  APP_PORT = 'APP_PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',
  AMQP_URL = 'AMQP_URL',
  AMQP_QUEUE = 'AMQP_QUEUE',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
}
